Homework Module #1
js-tasks-ru/jsbasic-20221114_fotex200 pull request #2
Opened 2022-11-23 01:06 UTC by Litsavkina

2022-11-23 01:07 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-11-23 11:34 UTC, SinimaWath requested changes

2022-11-23 11:34 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return false;
Если операция возвращает boolean, то нет необходимости в if
`return Boolean(name) && name.indexOf(' ') === -1 && name.length >= 4`

2022-11-23 11:34 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  if (str === undefined || str === null || str === '') return '';
можно упростить до:
```
if (!str) {
  return ''
}
```

2022-11-23 11:34 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return false;
`return str.includes("xxx") || str.includes("1xbet")`

2022-11-23 14:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-23 15:00 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-23 15:00 UTC, Litsavkina commented on 1-module/2-task/index.js
> +  return false;
Код обновлен и готов к проверке.

2022-11-23 15:00 UTC, Litsavkina commented on 1-module/3-task/index.js
> +  if (str === undefined || str === null || str === '') return '';
Код обновлен и готов к проверке.

2022-11-23 15:01 UTC, Litsavkina commented on 1-module/4-task/index.js
> +  return false;
Код обновлен и готов к проверке.

2022-11-24 11:06 UTC, SinimaWath requested changes
Из-за того, что есть добавленная но не решенная задача 2-1, то тесты не проходят

2022-11-24 11:06 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return false;
Тут лишний return false

2022-11-24 14:26 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-24 14:27 UTC, Litsavkina commented on 1-module/2-task/index.js
> +  return false;
Код подправлен

2022-11-27 16:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-27 16:42 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-27 16:44 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-27 16:46 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-27 16:46 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-27 17:25 UTC, SinimaWath commented
у тебя есть конфликт во задаче 3 второго модуля.

Сделай:
- `git pull upstream master`

 - Пофикси конфликт, убери в файлике разделители `=====` `<===` и т,д
 
 - Сделай коммит и запушь
 
 
 Вот тут хороший пример: https://www.youtube.com/watch?v=PXK1hIifpWU

2022-11-27 17:36 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-11-28 13:01 UTC, SinimaWath approved these changes

2022-11-28 13:02 UTC, merged